-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2025-04-02 00:42:44.806

-- tables
-- Table: BUCKETLIST_ITEMS
CREATE TABLE hr.BUCKETLIST_ITEMS (
    ITEM_ID serial  NOT NULL,
    description varchar(100)  NOT NULL,
    is_completee boolean  NOT NULL,
    created_timestamp timestamp  NOT NULL DEFAULT current_timestamp,
    USER_ID int  NOT NULL,
    BUCKETLIST_USERS_USER_ID int  NOT NULL,
    CONSTRAINT BUCKETLIST_ITEMS_pk PRIMARY KEY (ITEM_ID)
);

-- Table: BUCKETLIST_USERS
CREATE TABLE hr.BUCKETLIST_USERS (
    USER_ID serial  NOT NULL,
    email varchar(100)  NOT NULL,
    CONSTRAINT BUCKETLIST_USERS_pk PRIMARY KEY (USER_ID)
);

-- foreign keys
-- Reference: BUCKETLIST_ITEMS_BUCKETLIST_USERS (table: BUCKETLIST_ITEMS)
ALTER TABLE hr.BUCKETLIST_ITEMS ADD CONSTRAINT BUCKETLIST_ITEMS_BUCKETLIST_USERS
    FOREIGN KEY (USER_ID)
    REFERENCES hr.BUCKETLIST_USERS (USER_ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

